# Generated by Django 4.1.4 on 2022-12-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_fonoaudiologo_institucion_and_more'),
        ('medico_y_enfermera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna', verbose_name='Comuna'),
        ),
    ]
