# Generated by Django 4.1.4 on 2022-12-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id_diabetes', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Diabetes')),
                ('tipo_diabetes', models.CharField(max_length=100, verbose_name='Tipo Diabetes')),
            ],
        ),
    ]
