# Generated by Django 4.1.4 on 2022-12-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hipertension',
            fields=[
                ('id_hipertension', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Hipertension')),
                ('estado_hipertension', models.CharField(max_length=100, verbose_name='Estado Hipertension')),
            ],
        ),
    ]
