# Generated by Django 4.1.4 on 2022-12-21 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('usuario', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hipertension',
            fields=[
                ('id_hipertension', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Hipertension')),
                ('estado_hipertension', models.CharField(max_length=100, verbose_name='Estado Hipertension')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.IntegerField(verbose_name='Id Paciente')),
                ('username_paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut_paciente', models.CharField(max_length=10, verbose_name='Rut Paciente')),
                ('nombre_paciente', models.CharField(max_length=100, verbose_name='Nombre Paciente')),
                ('apellido_paciente', models.CharField(max_length=100, verbose_name='Apellido Paciente')),
                ('direccion_paciente', models.CharField(max_length=100, verbose_name='Direccion Paciente')),
                ('email_paciente', models.EmailField(max_length=100, verbose_name='Email Paciente')),
                ('telefono_paciente', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono Paciente')),
                ('whatsaap_paciente', models.CharField(max_length=9, verbose_name='Whatsaap Paciente')),
                ('celular_paciente', models.CharField(max_length=9, verbose_name='Celular Paciente')),
                ('telegram_paciente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Paciente')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna', verbose_name='Comuna')),
                ('diabetes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.diabetes', verbose_name='Diabetes')),
                ('hipertension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.hipertension', verbose_name='Hipertension')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.IntegerField(verbose_name='Id Familiar')),
                ('username_familiar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut_familiar', models.CharField(max_length=10, verbose_name='Rut Familiar')),
                ('nombre_familiar', models.CharField(max_length=100, verbose_name='Nombre Familiar')),
                ('apellido_familiar', models.CharField(max_length=100, verbose_name='Apellido Familiar')),
                ('direccion_familiar', models.CharField(max_length=100, verbose_name='Direccion Familiar')),
                ('email_familiar', models.CharField(max_length=100, verbose_name='Email Familiar')),
                ('telefono_familiar', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono Familiar')),
                ('whatsaap_familiar', models.CharField(max_length=9, verbose_name='Whatsaap Familiar')),
                ('celular_familiar', models.CharField(max_length=9, verbose_name='Celular Familiar')),
                ('telegram_familiar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Familiar')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna')),
            ],
        ),
    ]
