# Generated by Django 4.1.4 on 2023-02-02 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='username_familiar',
            field=models.OneToOneField(limit_choices_to={'tipo_usuario': 3}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='username_paciente',
            field=models.OneToOneField(limit_choices_to={'tipo_usuario': 1}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
