# Generated by Django 4.1.4 on 2022-12-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_hipertension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animo',
            fields=[
                ('id_Animo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Animo')),
                ('valor_animo', models.IntegerField(verbose_name='Valor Animo')),
                ('nombre_animo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Animo')),
            ],
        ),
    ]
