# Generated by Django 4.1.4 on 2023-02-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_familiar_username_familiar_and_more'),
    ]

    operations = [
     
    ]
