# Generated by Django 4.1.4 on 2022-12-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Monitoreo')),
                ('url_archivo_audio', models.FileField(upload_to='audios/')),
                ('jitter_ppq5', models.IntegerField(null=True, verbose_name='jitter ppq5')),
                ('jitter_rap', models.IntegerField(null=True, verbose_name='jitter rap')),
                ('maximum_pitch', models.IntegerField(null=True, verbose_name='maximum pitch')),
                ('error_jitter_ppq5', models.IntegerField(null=True, verbose_name='error jitter ppq5')),
                ('error_jitter_rap', models.IntegerField(null=True, verbose_name='error jitter rap')),
                ('error_maximum_pitch', models.IntegerField(null=True, verbose_name='error maximum pitch')),
                ('jitter_ppq5_IA', models.IntegerField(null=True, verbose_name='jitter ppq5')),
                ('jitter_rap_IA', models.IntegerField(null=True, verbose_name='jitter rap')),
                ('maximum_pitch_IA', models.IntegerField(null=True, verbose_name='maximum pitch')),
                ('error_jitter_ppq5_IA', models.IntegerField(null=True, verbose_name='error jitter ppq5')),
                ('error_jitter_rap_IA', models.IntegerField(null=True, verbose_name='error jitter rap')),
                ('error_maximum_pitch_IA', models.IntegerField(null=True, verbose_name='error maximum pitch')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Automonitoreo',
            fields=[
                ('id_monitoreo', models.AutoField(primary_key=True, serialize=False, verbose_name='id Monitoreo')),
                ('fecha_automonitoreo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Monitoreo')),
            ],
            options={
                'ordering': ['-fecha_automonitoreo'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Monitoreo')),
                ('anotaciones', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Anotaciones')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Comuna')),
                ('nombre_comuna', models.CharField(max_length=100, verbose_name='Nombre Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False, verbose_name='id Descuento')),
                ('descuento', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Descuento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('ticket_decuento', models.CharField(max_length=100, verbose_name='Direccion Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento_usado',
            fields=[
                ('id_descuento_usado', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Descuento Usado')),
                ('fecha_usado', models.DateField(verbose_name='Fecha Usado')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Documento')),
                ('titulo', models.CharField(max_length=1000, verbose_name='Titulo')),
                ('documento', models.FileField(upload_to='documentos/')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion')),
                ('qr', models.FileField(blank=True, null=True, upload_to='qr_documento/')),
            ],
        ),
        migrations.CreateModel(
            name='Dosis',
            fields=[
                ('id_dosis', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Dosis')),
                ('cantidad_dosis', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Cantidad Dosis')),
                ('descripcion', models.CharField(max_length=5, verbose_name='Descripcion')),
            ],
        ),
    ]
