# Generated by Django 4.1.4 on 2022-12-21 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico_y_enfermera', '0001_initial'),
        ('app', '0001_initial'),
        ('paciente', '0002_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('id_enfermera', models.IntegerField(verbose_name='Id Enfermera')),
                ('username_enfermera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut_enfermera', models.CharField(max_length=10, verbose_name='Rut Enfermera')),
                ('nombre_enfermera', models.CharField(max_length=100, verbose_name='Nombre Enfermera')),
                ('apellido_enfermera', models.CharField(max_length=100, verbose_name='Apellido Enfermera')),
                ('direccion_enfermera', models.CharField(max_length=100, verbose_name='Direccion Enfermera')),
                ('email_enfermera', models.EmailField(max_length=100, verbose_name='Email Enfermera')),
                ('telefono_enfermera', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono Enfermera')),
                ('whatsaap_enfermera', models.CharField(max_length=9, verbose_name='Whatsaap Enfermera')),
                ('celular_enfermera', models.CharField(max_length=9, verbose_name='Celular Enfermera')),
                ('telegram_enfermera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Enfermera')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna', verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_monitoreo',
            fields=[
                ('id_estado_monitoreo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id estado Monitoreo')),
                ('valor_automonitoreo', models.IntegerField(verbose_name='Valor Automonitoreo')),
                ('estado_monitoreo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Monitoreo')),
            ],
        ),
        migrations.CreateModel(
            name='Fonoaudiologo',
            fields=[
                ('id_fonoaudiologo', models.IntegerField(verbose_name='Id Usuario')),
                ('username_fonoaudiologo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut_fonoaudiologo', models.CharField(max_length=10, verbose_name='Rut fonoaudiologo')),
                ('nombre_fonoaudiologo', models.CharField(max_length=100, verbose_name='Nombre fonoaudiologo')),
                ('apellido_fonoaudiologo', models.CharField(max_length=100, verbose_name='Apellido fonoaudiologo')),
                ('direccion_fonoaudiologo', models.CharField(max_length=100, verbose_name='Direccion fonoaudiologo')),
                ('email_fonoaudiologo', models.CharField(max_length=100, verbose_name='Email fonoaudiologo')),
                ('telefono_fonoaudiologo', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono fonoaudiologo')),
                ('whatsaap_fonoaudiologo', models.CharField(max_length=9, verbose_name='Whatsaap fonoaudiologo')),
                ('celular_fonoaudiologo', models.CharField(max_length=9, verbose_name='Celular fonoaudiologo')),
                ('telegram_fonoaudiologo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram fonoaudiologo')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna', verbose_name='Comuna')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico_y_enfermera.institucion', verbose_name='Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Forma_farmaceutica',
            fields=[
                ('id_forma_farmaceutica', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Forma Farmaceutica')),
                ('forma_farmaceutica', models.CharField(max_length=100, verbose_name='Forma Farmaceutica')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Laboratorio')),
                ('laboratorio', models.CharField(max_length=100, verbose_name='Laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Marca')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Medicamento')),
                ('nombre_medicamento', models.CharField(max_length=100, verbose_name='Nombre Medicamento')),
                ('medida_medicamento', models.IntegerField(verbose_name='Medida Medicamento')),
                ('cantidad_comprimidos', models.IntegerField(verbose_name='Cantidad Medicamento')),
                ('forma_farmaceutica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.forma_farmaceutica', verbose_name='Forma_farmaceutica')),
                ('laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.laboratorio', verbose_name='Laboratorio')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.marca', verbose_name='Marca')),
            ],
            options={
                'ordering': ['-laboratorio'],
            },
        ),
        migrations.CreateModel(
            name='Neurologo',
            fields=[
                ('id_neurologo', models.IntegerField(verbose_name='Id Usuario')),
                ('username_neurologo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut_neurologo', models.CharField(max_length=10, verbose_name='Rut Neurologo')),
                ('nombre_neurologo', models.CharField(max_length=100, verbose_name='Nombre Neurologo')),
                ('apellido_neurologo', models.CharField(max_length=100, verbose_name='Apellido Neurologo')),
                ('direccion_neurologo', models.CharField(max_length=100, verbose_name='Direccion Neurologo')),
                ('email_neurologo', models.CharField(max_length=100, verbose_name='Email Neurologo')),
                ('telefono_neurologo', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono Neurologo')),
                ('whatsaap_neurologo', models.CharField(max_length=9, verbose_name='Whatsaap Neurologo')),
                ('celular_neurologo', models.CharField(max_length=9, verbose_name='Celular Neurologo')),
                ('telegram_neurologo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Neurologo')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico_y_enfermera.institucion', verbose_name='Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Receta')),
                ('fecha_receta', models.DateField(auto_now_add=True, verbose_name='Fecha Receta')),
                ('horario_medicamento', models.TimeField(verbose_name='Hora Medicamento')),
                ('dosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dosis', verbose_name='Dosis')),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.medicamento', verbose_name='Medicamento')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'ordering': ['horario_medicamento'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacion_consumo',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Recomendacion')),
                ('recomendacion', models.CharField(max_length=100, verbose_name='Recomendacion')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Region')),
                ('nombre_region', models.CharField(max_length=100, verbose_name='Nombre Region')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCorreos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=1400)),
                ('mensaje', models.CharField(max_length=1400)),
                ('dirigido', models.CharField(max_length=1400)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_farmaco',
            fields=[
                ('id_tipo_farmaco', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Tipo Farmaco')),
                ('tipo_farmaco', models.CharField(max_length=100, verbose_name='Tipo Farmaco')),
                ('descripcion_tipo_farmaco', models.CharField(max_length=400, verbose_name='Descripcion Tipo Farmaco')),
            ],
        ),
        migrations.CreateModel(
            name='Via_ingesta',
            fields=[
                ('id_via_ingesta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Via Ingesta')),
                ('via_ingesta', models.CharField(max_length=100, verbose_name='Via Ingesta')),
            ],
        ),
        migrations.CreateModel(
            name='Vocalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Monitoreo')),
                ('url_archivo_vocalizacion', models.FileField(upload_to='vocalizacion/')),
                ('duracion', models.IntegerField(null=True, verbose_name='Duracion')),
                ('bpminute', models.IntegerField(null=True, verbose_name='BPM Beats Per Minute ')),
                ('bpmeasure', models.IntegerField(null=True, verbose_name='Beats Per Measure')),
                ('comentario', models.CharField(max_length=500, null=True, verbose_name='Comentarios')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio_grabacion',
            fields=[
                ('id_recordatorio', models.AutoField(primary_key=True, serialize=False, verbose_name='Id recordatorio')),
                ('hora_recordatorio', models.TimeField(verbose_name='Hora Recordatorio')),
                ('receta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.receta', verbose_name='Receta')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Provincia')),
                ('nombre_provincia', models.CharField(max_length=100, verbose_name='Nombre Provincia')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region', verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Preregistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paciente', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut_paciente', models.CharField(max_length=10, verbose_name='Rut')),
                ('telefono_paciente', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono paciente')),
                ('email_paciente', models.EmailField(max_length=100, verbose_name='Email paciente')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Prere4gistro')),
                ('neurologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neurologo', verbose_name='Neurologo de Referencia')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Paciente_Documento',
            fields=[
                ('id_paciente_documento', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Documento')),
                ('autorizado', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Autorizacion')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.documento', verbose_name='Documento')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Neurologo_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_neurologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neurologo', verbose_name='Neurologo')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='recomendacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.recomendacion_consumo', verbose_name='Recomendacion_consumo'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tipo_farmaco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_farmaco', verbose_name='Tipo_farmaco'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='via_ingesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.via_ingesta', verbose_name='Via_ingesta'),
        ),
        migrations.CreateModel(
            name='Intensidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Monitoreo')),
                ('url_archivo_intensidad', models.FileField(upload_to='intensidad/')),
                ('intensidad', models.IntegerField(null=True, verbose_name='Intensidad')),
                ('mindb', models.IntegerField(null=True, verbose_name='Min dB')),
                ('maxdb', models.IntegerField(null=True, verbose_name='Max dB')),
                ('comentario', models.CharField(max_length=500, null=True, verbose_name='Comentarios')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Fonoaudiologo_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_fonoaudiologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fonoaudiologo', verbose_name='Fonoaudiologo')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_familiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.familiar', verbose_name='Familiar')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_animo',
            fields=[
                ('id_estado_animo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Estado Animo')),
                ('fecha_estado_animo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Estado Animo')),
                ('animo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.animo', verbose_name='Animo')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'ordering': ['-fecha_estado_animo'],
            },
        ),
        migrations.CreateModel(
            name='Enfermera_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_enfermera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enfermera', verbose_name='Enfermera')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermera_neurologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_enfermera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enfermera', verbose_name='Enfermera')),
                ('username_neurologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neurologo', verbose_name='Neurologo')),
            ],
        ),
        migrations.AddField(
            model_name='descuento_usado',
            name='descuento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.descuento', verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='descuento_usado',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.medicamento', verbose_name='Medicamento'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='username_enfermera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enfermera', verbose_name='Enfermera'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='username_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='automonitoreo',
            name='estado_monitoreo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estado_monitoreo', verbose_name='Estado_monitoreo'),
        ),
        migrations.AddField(
            model_name='automonitoreo',
            name='username_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='audio',
            name='username_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
    ]
