# Generated by Django 4.1.3 on 2022-11-25 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('id_enfermera', models.IntegerField(verbose_name='Id Enfermera')),
                ('username_enfermera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut_enfermera', models.CharField(max_length=10, verbose_name='Rut Enfermera')),
                ('nombre_enfermera', models.CharField(max_length=100, verbose_name='Nombre Enfermera')),
                ('apellido_enfermera', models.CharField(max_length=100, verbose_name='Apellido Enfermera')),
                ('direccion_enfermera', models.CharField(max_length=100, verbose_name='Direccion Enfermera')),
                ('email_enfermera', models.EmailField(max_length=100, verbose_name='Email Enfermera')),
                ('telefono_enfermera', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono Enfermera')),
                ('whatsaap_enfermera', models.CharField(max_length=9, verbose_name='Whatsaap Enfermera')),
                ('celular_enfermera', models.CharField(max_length=9, verbose_name='Celular Enfermera')),
                ('telegram_enfermera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Enfermera')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna', verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Monitoreo')),
                ('anotaciones', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Anotaciones')),
                ('username_enfermera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enfermera', verbose_name='Enfermera')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente', verbose_name='Paciente')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
