# Generated by Django 4.1.4 on 2022-12-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamento.forma_farmaceutica', verbose_name='Forma_farmaceutica'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamento.laboratorio', verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamento.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='recomendacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamento.recomendacion_consumo', verbose_name='Recomendacion_consumo'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='tipo_farmaco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamento.tipo_farmaco', verbose_name='Tipo_farmaco'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='via_ingesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamento.via_ingesta', verbose_name='Via_ingesta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='dosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamento.dosis', verbose_name='Dosis'),
        ),
        migrations.DeleteModel(
            name='Dosis',
        ),
        migrations.DeleteModel(
            name='Forma_farmaceutica',
        ),
        migrations.DeleteModel(
            name='Laboratorio',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Recomendacion_consumo',
        ),
        migrations.DeleteModel(
            name='Tipo_farmaco',
        ),
        migrations.DeleteModel(
            name='Via_ingesta',
        ),
    ]
