# Generated by Django 4.1.3 on 2022-11-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_enfermera_bitacora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermera_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_enfermera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enfermera', verbose_name='Enfermera')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente', verbose_name='Paciente')),
            ],
        ),
    ]
