# Generated by Django 4.1.4 on 2023-02-06 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_alter_familiar_email_familiar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fonoaudiologo', '0006_alter_fonoaudiologo_email_fonoaudiologo_and_more'),
        ('medicamento', '0012_rename_frecueniastock_medicamentosfull_frecuenciastock'),
        ('usuario', '0006_alter_usuario_tipo_usuario'),
        ('medico_y_enfermera', '0001_initial'),
        ('app', '0002_enfermera_enfermera_neurologo_enfermera_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('id_enfermera', models.IntegerField(verbose_name='Id Enfermera')),
                ('username_enfermera', models.OneToOneField(limit_choices_to={'tipo_usuario': 5}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut_enfermera', models.CharField(max_length=10, verbose_name='Rut Enfermera')),
                ('direccion_enfermera', models.CharField(max_length=100, verbose_name='Direccion Enfermera')),
                ('telefono_enfermera', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono Enfermera')),
                ('celular_enfermera', models.CharField(max_length=9, verbose_name='Celular Enfermera')),
                ('telegram_enfermera', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram Enfermera')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna', verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermera_neurologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_enfermera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enfermera', verbose_name='Enfermera')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermera_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_enfermera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enfermera', verbose_name='Enfermera')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_animo',
            fields=[
                ('id_estado_animo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Estado Animo')),
                ('fecha_estado_animo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Estado Animo')),
                ('animo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.animo', verbose_name='Animo')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'ordering': ['-fecha_estado_animo'],
            },
        ),
        migrations.CreateModel(
            name='Estado_monitoreo',
            fields=[
                ('id_estado_monitoreo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id estado Monitoreo')),
                ('valor_automonitoreo', models.IntegerField(verbose_name='Valor Automonitoreo')),
                ('estado_monitoreo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Monitoreo')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_familiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.familiar', verbose_name='Familiar')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Neurologo',
            fields=[
                ('id_neurologo', models.IntegerField(verbose_name='Id Usuario')),
                ('username_neurologo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut_neurologo', models.CharField(max_length=10, unique=True, verbose_name='Rut Neurologo')),
                ('nombre_neurologo', models.CharField(max_length=100, verbose_name='Nombre Neurologo')),
                ('apellido_neurologo', models.CharField(max_length=100, verbose_name='Apellido Neurologo')),
                ('direccion_neurologo', models.CharField(max_length=100, verbose_name='Direccion Neurologo')),
                ('email_neurologo', models.CharField(max_length=100, unique=True, verbose_name='Email Neurologo')),
                ('telefono_neurologo', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono Neurologo')),
                ('whatsaap_neurologo', models.CharField(max_length=9, verbose_name='Whatsaap Neurologo')),
                ('celular_neurologo', models.CharField(max_length=9, verbose_name='Celular Neurologo')),
                ('telegram_neurologo', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram Neurologo')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico_y_enfermera.institucion', verbose_name='Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Neurologo_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_neurologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neurologo', verbose_name='Neurologo')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_Documento',
            fields=[
                ('id_paciente_documento', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Documento')),
                ('autorizado', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Autorizacion')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.documento', verbose_name='Documento')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Preregistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paciente', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut_paciente', models.CharField(max_length=10, unique=True, verbose_name='Rut')),
                ('telefono_paciente', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono paciente')),
                ('email_paciente', models.EmailField(max_length=100, unique=True, verbose_name='Email paciente')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Preregistro')),
                ('terminos_uso', models.BooleanField(verbose_name='Acepta termino de uso')),
                ('neurologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neurologo', verbose_name='Neurologo de Referencia')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Provincia')),
                ('nombre_provincia', models.CharField(max_length=100, verbose_name='Nombre Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Receta')),
                ('fecha_receta', models.DateField(auto_now_add=True, verbose_name='Fecha Receta')),
                ('horario_medicamento', models.TimeField(verbose_name='Hora Medicamento')),
                ('dosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamento.dosis', verbose_name='Dosis')),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamento.medicamento', verbose_name='Medicamento')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'ordering': ['horario_medicamento'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio_grabacion',
            fields=[
                ('id_recordatorio', models.AutoField(primary_key=True, serialize=False, verbose_name='Id recordatorio')),
                ('hora_recordatorio', models.TimeField(verbose_name='Hora Recordatorio')),
                ('receta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.receta', verbose_name='Receta')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Region')),
                ('nombre_region', models.CharField(max_length=100, verbose_name='Nombre Region')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCorreos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=1400)),
                ('mensaje', models.CharField(max_length=1400)),
                ('dirigido', models.CharField(max_length=1400)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Terapias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios', models.CharField(max_length=300)),
                ('fonoaudiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonoaudiologo.fonoaudiologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_terapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='Dosis',
        ),
        migrations.AddField(
            model_name='automonitoreo',
            name='username_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='username_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamento.medicamento', verbose_name='Medicamento'),
        ),
        migrations.AddField(
            model_name='descuento_usado',
            name='descuento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.descuento', verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='descuento_usado',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='ticket_decuento',
            field=models.CharField(max_length=100, verbose_name='ticket de descuento'),
        ),
        migrations.AddField(
            model_name='terapias',
            name='tipo_terapia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_terapia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='enfermera_neurologo',
            name='username_neurologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neurologo', verbose_name='Neurologo'),
        ),
        migrations.AddField(
            model_name='automonitoreo',
            name='estado_monitoreo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estado_monitoreo', verbose_name='Estado_monitoreo'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='username_enfermera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enfermera', verbose_name='Enfermera'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.provincia', verbose_name='Provincia'),
        ),
        migrations.AddConstraint(
            model_name='preregistro',
            constraint=models.CheckConstraint(check=models.Q(('terminos_uso__gte', 1)), name='Debe aceptar los terminos de uso'),
        ),
    ]
