# Generated by Django 4.1.3 on 2022-11-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_enfermera_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fecha_receta',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Receta'),
        ),
    ]
