# Generated by Django 4.1.3 on 2022-11-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_receta_fecha_receta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ['-laboratorio']},
        ),
    ]
