# Generated by Django 4.1.4 on 2022-12-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fonoaudiologo', '0001_initial'),
        ('app', '0004_alter_descuento_medicamento_alter_receta_medicamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoaudiologo_paciente',
            name='username_fonoaudiologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fonoaudiologo.fonoaudiologo', verbose_name='Fonoaudiologo'),
        ),
        migrations.DeleteModel(
            name='Fonoaudiologo',
        ),
    ]
