# Generated by Django 4.1.4 on 2022-12-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_fonoaudiologo_paciente_username_fonoaudiologo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fonoaudiologo_paciente',
        ),
    ]
