# Generated by Django 4.1.3 on 2022-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_medicamento_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte_audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=100, verbose_name='Nombre tipo usuario')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
    ]
