# Generated by Django 4.1.4 on 2022-12-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_fonoaudiologo_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
