# Generated by Django 4.1.4 on 2022-12-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocalizacion',
            name='username_paciente',
        ),
        migrations.DeleteModel(
            name='Intensidad',
        ),
        migrations.DeleteModel(
            name='Vocalizacion',
        ),
    ]
