# Generated by Django 4.1.3 on 2022-12-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_reporte_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Documento')),
                ('documento', models.FileField(upload_to='documentos/')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='id_tipo_usuario',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id tipo usuario'),
        ),
        migrations.CreateModel(
            name='Paciente_Documento',
            fields=[
                ('id_paciente_documento', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Documento')),
                ('autorizado', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Autorizacion')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.documento', verbose_name='Documento')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente', verbose_name='Paciente')),
            ],
        ),
    ]
