# Generated by Django 4.1.4 on 2022-12-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_vocalizacion_username_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermera',
            name='apellido_enfermera',
        ),
        migrations.RemoveField(
            model_name='enfermera',
            name='email_enfermera',
        ),
        migrations.RemoveField(
            model_name='enfermera',
            name='nombre_enfermera',
        ),
    ]
