# Generated by Django 4.1.3 on 2022-12-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_documento_alter_tipo_usuario_id_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente_documento',
            old_name='paciente',
            new_name='username_paciente',
        ),
    ]
