# Generated by Django 4.1.4 on 2022-12-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_enfermera_apellido_enfermera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermera',
            name='whatsaap_enfermera',
        ),
    ]
