# Generated by Django 4.1.3 on 2022-12-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_paciente_paciente_documento_username_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.CharField(max_length=1000, verbose_name='Descripcion'),
        ),
    ]
