# Generated by Django 4.1.3 on 2022-12-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_documento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='qr',
            field=models.FileField(blank=True, null=True, upload_to='qr_documento/'),
        ),
        migrations.AddField(
            model_name='documento',
            name='titulo',
            field=models.CharField(default=1, max_length=1000, verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente_documento',
            name='autorizado',
            field=models.BooleanField(default=True),
        ),
    ]
