# Generated by Django 4.1.3 on 2022-12-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_documento_qr_documento_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=1000, verbose_name='Titulo'),
        ),
    ]
