# Generated by Django 4.1.4 on 2022-12-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_preregistro_terminos_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistro',
            name='terminos_uso',
            field=models.BooleanField(verbose_name='Acepta termino de uso'),
        ),
        migrations.AddConstraint(
            model_name='preregistro',
            constraint=models.CheckConstraint(check=models.Q(('terminos_uso__gte', 1)), name='Debe aceptar los terminos de uso'),
        ),
    ]
