# Generated by Django 4.1.4 on 2023-01-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_preregistro_terminos_uso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='ticket_decuento',
            field=models.CharField(max_length=100, verbose_name='ticket de descuento'),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Preregistro'),
        ),
    ]
