# Generated by Django 4.1.4 on 2023-01-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_initial'),
        ('fonoaudiologo', '0004_vocalizacion_intensidad'),
        ('app', '0013_alter_descuento_ticket_decuento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_terapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Terapias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios', models.CharField(max_length=300)),
                ('fonoaudiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonoaudiologo.fonoaudiologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('tipo_terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_terapia')),
            ],
        ),
    ]
