# Generated by Django 4.1.3 on 2022-12-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_preregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistro',
            name='neurologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neurologo', verbose_name='Neurologo de Referencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario', verbose_name='Tipo Usuario'),
        ),
    ]
