# Generated by Django 4.1.3 on 2022-12-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_preregistro_neurologo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preregistro',
        ),
    ]
