# Generated by Django 4.1.3 on 2022-12-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_preregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preregistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paciente', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut_paciente', models.CharField(max_length=10, verbose_name='Rut')),
                ('telefono_paciente', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono paciente')),
                ('email_paciente', models.EmailField(max_length=100, verbose_name='Email paciente')),
                ('neurologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neurologo', verbose_name='Neurologo de Referencia')),
            ],
        ),
    ]
