# Generated by Django 4.1.3 on 2022-12-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_preregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermera_neurologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_enfermera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enfermera', verbose_name='Enfermera')),
                ('username_neurologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neurologo', verbose_name='Paciente')),
            ],
        ),
    ]
