# Generated by Django 4.1.3 on 2022-12-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_enfermera_neurologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='error_jitter_ppq5_IA',
            field=models.IntegerField(null=True, verbose_name='error jitter ppq5'),
        ),
        migrations.AddField(
            model_name='audio',
            name='error_jitter_rap_IA',
            field=models.IntegerField(null=True, verbose_name='error jitter rap'),
        ),
        migrations.AddField(
            model_name='audio',
            name='error_maximum_pitch_IA',
            field=models.IntegerField(null=True, verbose_name='error maximum pitch'),
        ),
        migrations.AddField(
            model_name='audio',
            name='jitter_ppq5_IA',
            field=models.IntegerField(null=True, verbose_name='jitter ppq5'),
        ),
        migrations.AddField(
            model_name='audio',
            name='jitter_rap_IA',
            field=models.IntegerField(null=True, verbose_name='jitter rap'),
        ),
        migrations.AddField(
            model_name='audio',
            name='maximum_pitch_IA',
            field=models.IntegerField(null=True, verbose_name='maximum pitch'),
        ),
    ]
