# Generated by Django 4.1.3 on 2022-12-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_audio_error_jitter_ppq5_ia_audio_error_jitter_rap_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosis',
            name='descripcion',
            field=models.CharField(default=1, max_length=5, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
