# Generated by Django 4.1.3 on 2022-12-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_dosis_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='preregistro',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Prere4gistro'),
        ),
    ]
