# Generated by Django 4.1.3 on 2022-12-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_usuario_options_preregistro_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCorreos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=1400)),
                ('mensaje', models.CharField(max_length=1400)),
                ('dirigido', models.CharField(max_length=1400)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
