# Generated by Django 4.1.3 on 2022-12-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_registrocorreos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preregistro',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='registrocorreos',
            options={'ordering': ['-timestamp']},
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=100, verbose_name='Nombre Institución')),
                ('descripcion', models.CharField(max_length=2000, verbose_name='Descripción Institución')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna', verbose_name='Comuna')),
            ],
        ),
        migrations.AddField(
            model_name='fonoaudiologo',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.institucion', verbose_name='Institucion'),
        ),
    ]
