# Generated by Django 4.1.3 on 2022-12-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_preregistro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurologo',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.institucion', verbose_name='Institucion'),
        ),
    ]
