# Generated by Django 4.1.3 on 2022-12-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_neurologo_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermera_neurologo',
            name='username_neurologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neurologo', verbose_name='Neurologo'),
        ),
    ]
