# Generated by Django 4.1.4 on 2022-12-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_enfermera_neurologo_username_neurologo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Tipo_Usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
