# Generated by Django 4.1.4 on 2022-12-20 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
        ('app', '0025_remove_usuario_groups_remove_usuario_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='diabetes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.diabetes', verbose_name='Diabetes'),
        ),
        migrations.DeleteModel(
            name='Diabetes',
        ),
    ]
