# Generated by Django 4.1.4 on 2022-12-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_hipertension'),
        ('app', '0026_alter_paciente_diabetes_delete_diabetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='hipertension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.hipertension', verbose_name='Hipertension'),
        ),
        migrations.DeleteModel(
            name='Hipertension',
        ),
    ]
