# Generated by Django 4.1.4 on 2022-12-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_animo'),
        ('app', '0027_alter_paciente_hipertension_delete_hipertension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_animo',
            name='animo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.animo', verbose_name='Animo'),
        ),
        migrations.DeleteModel(
            name='Animo',
        ),
    ]
