# Generated by Django 4.1.4 on 2022-12-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico_y_enfermera', '0001_initial'),
        ('app', '0028_alter_estado_animo_animo_delete_animo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoaudiologo',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico_y_enfermera.institucion', verbose_name='Institucion'),
        ),
        migrations.AlterField(
            model_name='neurologo',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico_y_enfermera.institucion', verbose_name='Institucion'),
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
    ]
