# Generated by Django 4.1.4 on 2022-12-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminosDeUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='documentos/')),
            ],
        ),
    ]
