# Generated by Django 4.1.4 on 2023-01-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_terminosdeuso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TerminosDeUso',
        ),
    ]
