# Generated by Django 4.1.4 on 2023-02-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_delete_terminosdeuso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.tipo_usuario', verbose_name='Tipo Usuario'),
        ),
    ]
