# Generated by Django 4.1.4 on 2022-12-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosis',
            fields=[
                ('id_dosis', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Dosis')),
                ('cantidad_dosis', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Cantidad Dosis')),
                ('descripcion', models.CharField(max_length=5, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Forma_farmaceutica',
            fields=[
                ('id_forma_farmaceutica', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Forma Farmaceutica')),
                ('forma_farmaceutica', models.CharField(max_length=100, verbose_name='Forma Farmaceutica')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Laboratorio')),
                ('laboratorio', models.CharField(max_length=100, verbose_name='Laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Marca')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion_consumo',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Recomendacion')),
                ('recomendacion', models.CharField(max_length=100, verbose_name='Recomendacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_farmaco',
            fields=[
                ('id_tipo_farmaco', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Tipo Farmaco')),
                ('tipo_farmaco', models.CharField(max_length=100, verbose_name='Tipo Farmaco')),
                ('descripcion_tipo_farmaco', models.CharField(max_length=400, verbose_name='Descripcion Tipo Farmaco')),
            ],
        ),
        migrations.CreateModel(
            name='Via_ingesta',
            fields=[
                ('id_via_ingesta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Via Ingesta')),
                ('via_ingesta', models.CharField(max_length=100, verbose_name='Via Ingesta')),
            ],
        ),
    ]
