# Generated by Django 4.1.4 on 2023-01-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0003_medicamentosfull'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentosfull',
            name='sku',
            field=models.CharField(default='ff', max_length=200, verbose_name='sku'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamentosfull',
            name='stockDiario',
            field=models.CharField(default='ff', max_length=200, verbose_name='stock diario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamentosfull',
            name='stockSistema',
            field=models.CharField(default='ff', max_length=200, verbose_name='stock de sistema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamentosfull',
            name='sucursal',
            field=models.CharField(default='ff', max_length=200, verbose_name='sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamentosfull',
            name='timestamp',
            field=models.CharField(default='ff', max_length=200, verbose_name='timestamp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamentosfull',
            name='forma_farmaceutica',
            field=models.CharField(default='ff', max_length=200, verbose_name='forma formaceutica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamentosfull',
            name='laboratorio',
            field=models.CharField(default='ff', max_length=200, verbose_name='laboratorio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamentosfull',
            name='marca',
            field=models.CharField(default='ff', max_length=200, verbose_name='marca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamentosfull',
            name='recomendacion',
            field=models.CharField(default='ff', max_length=200, verbose_name='recomendacion de consumo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamentosfull',
            name='tipo_farmaco',
            field=models.CharField(default='ff', max_length=200, verbose_name='tipo de farmaco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamentosfull',
            name='via_ingesta',
            field=models.CharField(default='ff', max_length=200, verbose_name='via de ingesta'),
            preserve_default=False,
        ),
    ]
