# Generated by Django 4.1.4 on 2023-01-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0004_medicamentosfull_sku_medicamentosfull_stockdiario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentosfull',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
    ]
