# Generated by Django 4.1.4 on 2023-01-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0006_medicamentosfull_fecha_actua'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamentosfull',
            old_name='fecha_actua',
            new_name='fecha_actu_stock',
        ),
    ]
