# Generated by Django 4.1.4 on 2023-01-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0007_rename_fecha_actua_medicamentosfull_fecha_actu_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentosfull',
            name='medida_medicamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida Medicamento'),
        ),
    ]
