# Generated by Django 4.1.4 on 2023-01-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0009_alter_medicamentosfull_cantidad_comprimidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentosfull',
            name='frecueniaStock',
            field=models.CharField(default='semanal', max_length=200, verbose_name='frecuencia de stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamentosfull',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion'),
        ),
    ]
