# Generated by Django 4.1.4 on 2023-02-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0010_medicamentosfull_frecueniastock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentosfull',
            name='frecueniaStock',
            field=models.CharField(max_length=200, null=True, verbose_name='frecuencia de stock'),
        ),
    ]
