# Generated by Django 4.1.4 on 2023-02-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0011_alter_medicamentosfull_frecueniastock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamentosfull',
            old_name='frecueniaStock',
            new_name='frecuenciaStock',
        ),
    ]
