# Generated by Django 4.1.4 on 2022-12-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_initial'),
        ('fonoaudiologo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonoaudiologo_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_fonoaudiologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fonoaudiologo.fonoaudiologo', verbose_name='Fonoaudiologo')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
        ),
    ]
