# Generated by Django 4.1.4 on 2022-12-21 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_initial'),
        ('fonoaudiologo', '0002_fonoaudiologo_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Monitoreo')),
                ('url_archivo_audio', models.FileField(upload_to='audios/')),
                ('jitter_ppq5', models.IntegerField(null=True, verbose_name='jitter ppq5')),
                ('jitter_rap', models.IntegerField(null=True, verbose_name='jitter rap')),
                ('maximum_pitch', models.IntegerField(null=True, verbose_name='maximum pitch')),
                ('error_jitter_ppq5', models.IntegerField(null=True, verbose_name='error jitter ppq5')),
                ('error_jitter_rap', models.IntegerField(null=True, verbose_name='error jitter rap')),
                ('error_maximum_pitch', models.IntegerField(null=True, verbose_name='error maximum pitch')),
                ('jitter_ppq5_IA', models.IntegerField(null=True, verbose_name='jitter ppq5')),
                ('jitter_rap_IA', models.IntegerField(null=True, verbose_name='jitter rap')),
                ('maximum_pitch_IA', models.IntegerField(null=True, verbose_name='maximum pitch')),
                ('error_jitter_ppq5_IA', models.IntegerField(null=True, verbose_name='error jitter ppq5')),
                ('error_jitter_rap_IA', models.IntegerField(null=True, verbose_name='error jitter rap')),
                ('error_maximum_pitch_IA', models.IntegerField(null=True, verbose_name='error maximum pitch')),
                ('username_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
