# Generated by Django 4.1.4 on 2023-02-02 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fonoaudiologo', '0004_vocalizacion_intensidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoaudiologo',
            name='username_fonoaudiologo',
            field=models.OneToOneField(limit_choices_to={'tipo_usuario': 4}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
