# Generated by Django 4.1.4 on 2023-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonoaudiologo', '0005_alter_fonoaudiologo_username_fonoaudiologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoaudiologo',
            name='email_fonoaudiologo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Email fonoaudiologo'),
        ),
        migrations.AlterField(
            model_name='fonoaudiologo',
            name='rut_fonoaudiologo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Rut fonoaudiologo'),
        ),
        migrations.AlterField(
            model_name='fonoaudiologo',
            name='telegram_fonoaudiologo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram fonoaudiologo'),
        ),
    ]
